import Head from 'next/head'
import Navbar from "@/components/Navbar";
import Link from 'next/link';



export default function Prohibited() {
  return (
    <>
      <Head>
        <title>trexco</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar />
      </div>

     

      <section className='container'>
        <div className='content'>
       
       
<h1>PROHIBITED ITEMS &amp; PACKING RESTRICTIONS</h1>
<p>We would not be able to transport any items that fall within the following categories. If in any doubt whatsoever, please contact us for confirmation.</p>
<p></p>
<p>Prohibited items:</p>
<p></p>
<ul>
<p><strong>All hazardous goods</strong></p>
</ul>
<ul>
<p>Livestock or any other living creature</p>
</ul>
<ul>
<p>Controlled drugs</p>
</ul>
<ul>
<p>Machinery that contains oil</p>
</ul>
<ul>
<p>Fireworks</p>
</ul>
<ul>
<p>All flammable compressed gases</p>
</ul>
<ul>
<p>Any product or materials that may be dangerous or hazardous to handling staff</p>
</ul>
<p></p>
<p>Restricted items across Europe:</p>
<p></p>
<ul>
<p><strong>Alcohol - An inventory must detail the exact number and size of bottles, exact alcoholic strength in percent and value of each bottle.</strong></p>
</ul>
<ul>
<p>Tobacco, Tea, Coffee, Toilet waters, Perfumes, Foodstuffs in large quantities.</p>
</ul>
<ul>
<p>Electronic items inc. Computers, Media (cd's, videos dvd's blu-rays etc and Stereos, must show serial number and provide proof of purchase date).</p>
</ul>
<ul>
<p>Large amounts of handcrafts, Aerosols, Hazardous goods in certain quantities.</p>
</ul>
<p></p>
<p>Prohibited items across Europe:</p>
<p></p>
<ul>
<p><strong>Firearms, Ammunition, Explosives,</strong></p>
</ul>
<ul>
<p>Drugs and Narcotics,</p>
</ul>
<ul>
<p>Live Plants,</p>
</ul>
<ul>
<p>Any protected animal or species ie. Ivory, Snakeskin, Leopard fur.</p>
</ul>
<ul>
<p>Pornographic material,</p>
</ul>
<ul>
<p>Absinthe, Methyl alcohol and pure alcohol,</p>
</ul>
<ul>
<p>Radioactive material,</p>
</ul>
<ul>
<p>Wine, Grape juice and other various food stuffs in large quantity</p>
</ul>
<ul>
<p>Paintball guns and airsoft rifles.</p>
</ul>
<p></p>
<p>PLEASE NOTE: All engines, gearboxes and other car parts are safe to be shipped providing they have been fully drained of all oil and fluids.</p>
<p></p>
<p>if in doubt please give us a call on +44 2070961031</p>
<p>PACKING RESTRICTIONS</p>
<p>Is your responsibility to ensure the goods are safely packed and stacked on the Trexx box. All details must have been entered correctly on the booking page including your contact telephone number at collection and destination, as well as your goods packed in accordance with the following specifications. Failure to do so may result in refusal to collect the Trexx box, if the driver deems the goods or the way they have been packaged to be unsafe.</p>
<p></p>
<p>The packaged goods:</p>
<p>MUST be stable when packed or placed inside</p>
<p>MUST NOT compromise the structure of the box</p>
<p>MUST NOT exceed the weight of 600kg</p>
<p>MUST be firmly and properly secured&nbsp;</p>
<p>MUST be sufficiently packaged to protect the goods</p>
<p><br /><br /></p>
      
       </div>
      </section>
	

    



      


      

      
      <article class="footer">
        <div className='columns'>
        <article class="column">
          <h3>FAQ</h3>
          <ul>
              <li><Link href='faq'>FAQ</Link></li>
              <li><Link href='how'>How it works</Link></li>
              <li><Link href='contact'>Contact us</Link></li>
          </ul>
        </article>
        <article class="column">
          <h3>terms</h3>
          <ul>
               <li><Link href='prohibited'>Prohibited items</Link></li>
              <li><Link href='privacy'>Privacy policy</Link></li>
              <li><Link href='terms'>Terms & conditions</Link></li>
            </ul>   
        </article>
        </div>
      </article>






    </>
  )
}
