import Head from 'next/head'
import Navbar from "@/components/Navbar";
import Link from 'next/link';



export default function How() {
  return (
    <>
      <Head>
        <title>trexco</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Navbar />
      </div>

     

	<title>Terms &amp; Conditions</title>


	<h1>Terms &amp; Conditions</h1>
	<p>Please note that Trexco offers no guarantee to the charges applicable at the destination. Destination charges are outside of Trexco’s control and any figures quoted by Trexco are an indication only.</p>
	<h2>1. Definitions</h2>
	<ol>
		<li>Box means a packed box, pallet, pallet box, shipping container or any other item which Trexco agrees in writing may be transported by Trexco in accordance with these Terms;</li>
		<li>Collection Address means the address notified by the Customer to Trexco and which Trexco in its entire discretion agrees is where the Boxes are to be sent, positioned or collected from;</li>
		<li>Contract means the contract between the Customer and Trexco for the Services;</li>
		<li>Customer means the person who accepts Trexco’s quotation for the Services;</li>
		<li>Delivery Address means the address or port / airport notified by the Customer to Trexco and which Trexco in its entire discretion agrees is where the Boxes are to be delivered to or such substituted address as Trexco shall in its entire discretion decide;</li>
		<li>Force Majeure Event means any event beyond the reasonable control of Trexco including, without limitation, fire, flood, storm, tempest, inclement weather, acts of God, war, civil war or national emergency, protests, riot, civil commotion, acts of terrorism, malicious damage, compliance with law or governmental order, rule or regulation or direction, accident, fuel shortage, lock-out, strikes and other industrial disputes (whether or not relating to Trexco workforce) and restraints or delays affecting carriers.</li>
		<li>Prohibited Item means any single item which value exceeds £2500.00 Sterling, perishable goods, food stuffs of any description, liquids of any description, tobacco or similar products, hazardous materials or substances included but not limited to paint, matches, aerosol cans, gas canisters or other flammable materials, firearms and ammunition, plants or soil samples of any kind, live or stuffed animals, non-prescription drugs or medicines, corrosive materials or substances and explosives or pornography of any description, or any other article where importation of the article is restricted or prohibited at the destination by law or regulation;</li>
		<li>Services means the collection of the Boxes from the Collection Address and the transportation of Boxes from the Collection Address to the Delivery Address;</li>
		<li>Terms means these Terms and Conditions;</li>
		<li>Trexco means Trexco International Limited, its agents, subcontractors and employees;</li>
		<li>Website means www.trexco.net, www.trexxbox.com, www.trexx.co</li>
	</ol>
	<h2>2. Application</h2>
	<p>2.1 - These Terms shall govern and be incorporated in every Contract made by or on behalf of Trexco and the Customer. They shall apply in place of and prevail over any terms and conditions (whether or not in conflict or inconsistent with these Terms) contained or referred to in any documentation submitted by the Customer or in correspondence or elsewhere or implied by trade, custom, practise or course of dealing.</p>
	<p>2.2 - These terms do not affect your statutory rights as a consumer.</p>
	<h2>3. Prices</h2>
	

    



      


      

      
      <article className="footer">
        <div className='columns'>
        <article className="column">
          <h3>FAQ</h3>
          <ul>
              <li link href='#faq'>FAQ</li>
              <li link href='#how'>How it works</li>
              <li link href='#contact'>Contact us</li>
          </ul>
        </article>
        <article className="column">
          <h3>terms</h3>
          <ul>
              <li link href='#prohibited'>Prohibited items</li>
              <li link href='#privacy'>Privacy policy</li>
              <li link href='#terms'>Terms & conditions</li>
            </ul>   
        </article>
        </div>
      </article>






    </>
  )
}
